// <auto-generated />
using ApiCampeonatos.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace ApiCampeonatos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("ApiCampeonatos.Data.Campeonato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Campeonatos");
                });

            modelBuilder.Entity("ApiCampeonatos.Data.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CampeonatoId")
                        .HasColumnType("int");

                    b.Property<string>("Jogada")
                        .HasColumnType("longtext");

                    b.Property<string>("Resultado")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CampeonatoId");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("ApiCampeonatos.Data.Jogo", b =>
                {
                    b.HasOne("ApiCampeonatos.Data.Campeonato", null)
                        .WithMany("Jogadas")
                        .HasForeignKey("CampeonatoId");
                });

            modelBuilder.Entity("ApiCampeonatos.Data.Campeonato", b =>
                {
                    b.Navigation("Jogadas");
                });
#pragma warning restore 612, 618
        }
    }
}
